### ISSUE TITLE
Improve experience

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid_stats#18]
- Add retrying to `fetchData` 
- Ignore offline networks (as it blocks the entire experience)
- Show meaningful error messages
- Add `Refresh` button on (top right corner)
- Add  query filter to fetch only online results `?status=up`

**Comment by MohamedElmdary** [comment]
@maayarosama what is the state of this issue ?

**Comment by zaelgohary** [comment]
@MohamedElmdary the refresh button should refresh the whole page or the map only?

**Comment by MohamedElmdary** [comment]
@zaelgohary should fetch all data again

**Comment by maayarosama** [comment]
Retrying to fetchData is done, it tries to fetch the data three times and after that the error message is returned.
Showing meaningful error messages is also done as the error message returned from the fetching data on fail is what's shown to the user 
the refresh button on (top right corner) is halfway done, the functionality is working but the button needs some styling.
Adding query filter to fetch only online results ?status=up is done
