### ISSUE TITLE
odd spacing in the navbar

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid_stats#26]
![image](https://user-images.githubusercontent.com/64129/177120217-71407db2-5fdf-4261-9e42-4c56094be8c9.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The odd spacing is not there anymore.

![image](https://user-images.githubusercontent.com/101194226/184859397-e3db3d24-de63-4741-8ece-ff7944e657d4.png)
