### ISSUE TITLE
remove online suffix

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid_stats#27]
![image](https://user-images.githubusercontent.com/64129/177205012-0d155358-247d-4601-a108-1352f1bd7053.png)

**Comment by mohamedamer453** [comment]
`Online` suffix was removed from the `CPU` card but it's still present in the `RAM` & `Gateways` cards.

![image](https://user-images.githubusercontent.com/101194226/184864128-af18f027-11cf-4be3-9d12-aa254f1d8c66.png)

**Comment by khaledyoussef24** [comment]
still found in https://explorer.dev.grid.tf/
and in https://stats.grid.tf/
![Screenshot from 2022-08-23 02-40-59](https://user-images.githubusercontent.com/110984055/186043698-dce985d6-c8e4-405c-ae33-c151ceeda55b.png)
![Screenshot from 2022-08-23 02-43-01](https://user-images.githubusercontent.com/110984055/186043849-0de2ec97-69a7-403f-a7e8-d12db77ad9a1.png)

**Comment by xmonader** [comment]
I just merged the PR, it awaits on a release an deployment

**Comment by khaledyoussef24** [comment]
verified 

the online suffix is now removed


![Image](https://user-images.githubusercontent.com/110984055/187217012-2bb46739-aae1-4089-b686-73735ffaa386.png)
