### ISSUE TITLE
Country count too high

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid_stats#30]
Currently, the country count is shown as 140. Unified explorer shows only 81, but actually this is also too high since there is duplication of countries reported by their full name and country code (BE, EG, etc.).

**Comment by mohamedamer453** [comment]
Verified on devnet.

The countries count was fixed.

![image](https://user-images.githubusercontent.com/101194226/184883114-b6b9a6df-cb62-4ace-8663-7c3471d3f2ce.png)

however there's still a small issue with duplicate country names being double counted and it'll be followed in #39
