### ISSUE TITLE
live support

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid_stats#32]
```
<script type="text/javascript"> window.$crisp = []; window.CRISP_WEBSITE_ID = "1a5a5241-91cb-4a41-8323-5ba5ec574da0"; (function () { d = document; s = d.createElement("script"); s.src = "https://client.crisp.chat/l.js"; s.async = 1; d.getElementsByTagName("head")[0].appendChild(s); })(); </script>
```

**Comment by mohamedamer453** [comment]
Verified on devnet.

The live support button was added.

![image](https://user-images.githubusercontent.com/101194226/184864400-cec8c43a-7c92-4251-8c0f-d6afcbd58d49.png)

![image](https://user-images.githubusercontent.com/101194226/184864454-cd0466df-9daa-4236-a961-0ea1c58def79.png)
