### ISSUE TITLE
RAM card doesn't display correctly

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid_stats#35]
RAM card styling needs to be fixed.

![image](https://user-images.githubusercontent.com/40770501/184176171-795edea7-1d76-4168-91a1-62f06c431177.png)

**Comment by mohamedamer453** [comment]
The issue is still there when the table header exceeds the width of the window the black bars re appear again in the table

![image](https://user-images.githubusercontent.com/101194226/184874518-fa035bec-b6fc-41f1-95ae-ae151b14d813.png)

**Comment by khaledyoussef24** [comment]
The issue is still there when the table header exceeds the width of the window the black bars re appear again in the table


![Image](https://user-images.githubusercontent.com/110984055/187218901-8ddc07c9-ea8d-4d54-b0bc-7724fd6c6159.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The issue was fixed and the black bars are not visible anymore

![image](https://user-images.githubusercontent.com/101194226/187455207-cdda97d4-c719-4902-8974-75caad2df299.png)
