### ISSUE TITLE
Grid2 stats are not added in CPU value

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid_stats#38]
### Description

The `CPU` stats that's displayed in [stats.grid.tf](https://stats.grid.tf/) doesn't have the [grid2](https://explorer.grid.tf/) stats added. so  for the sake of consistency [grid2](https://explorer.grid.tf/) stats should be added.

The displayed `CPU` value is `59466` which is `444(dev) + 836(test) + 58186(main) `  without the value of grid2 

![image](https://user-images.githubusercontent.com/101194226/184637817-68e9130f-ddd2-4ff0-a9d7-4160615d0e98.png)

![image](https://user-images.githubusercontent.com/101194226/184637954-d5771f93-419b-4fe2-9826-178ec7ef9ca0.png)

**Comment by khaledyoussef24** [comment]
still the same problem found
420 cores on devnet
844 cores on testnet
58724 cores on main 
the total of 59988 cores  so the grid cores aren't calculated

![Screenshot from 2022-08-23 02-43-01](https://user-images.githubusercontent.com/110984055/186044106-d77c75cb-e521-4222-b95f-fccc0e55baa0.png)
![Screenshot from 2022-08-23 02-46-13](https://user-images.githubusercontent.com/110984055/186044118-b96b449b-40cb-4989-9147-9d502b2cd288.png)

**Comment by khaledyoussef24** [comment]
###verified 

The displayed CPU value is '68721' which is '449'(dev) + '840'(test) + '59668'(main) +'7952' (grid2)
values were from from gridproxy of [test](https://gridproxy.test.grid.tf/stats?status=up) & [devnet](https://gridproxy.dev.grid.tf/stats?status=up) & [mainnet](https://gridproxy.grid.tf/stats?status=up) & [grid2](https://explorer.grid.tf/)
which is equal = '68918' .
