### ISSUE TITLE
Update tf-map from v0.0.3 to v0.0.4 to fix wrong country name

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid_stats#43]
version 0.0.4 link https://cdn.jsdelivr.net/gh/threefoldtech/tf-map@0.0.4/dist/tf-map.js

**Comment by mohamedamer453** [comment]
Verified on devnet.

The tf-map was updated to the latest version and the wrong country names like `Vietnam` was fixed.

![image](https://user-images.githubusercontent.com/101194226/187253139-744a888c-cde7-4c52-9ea9-3f6d297d2569.png)
