### ISSUE TITLE
Remove grid2 numbers

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid_stats#48]
### Description
Remove all statistics numbers from grid2.

**Comment by mohamedamer453** [comment]
Verified on devnet.

grid2 statistics were removed from the stats. and now all the stats are the sum of  [devnet](https://gridproxy.dev.grid.tf/stats?status=up), [testnet](https://gridproxy.test.grid.tf/stats?status=up), and [mainnet](https://gridproxy.grid.tf/stats?status=up).

![image](https://user-images.githubusercontent.com/101194226/187618786-2f3259ba-8510-4afe-8d7e-5f7561e3d947.png)


ex: CPUs = `421(dev) + 800(test) + 59890(main) = 61111`

SSD = `15927885742080(dev) + 26357568749568(test) + 8965889784382976(main) =9008175238874624 bytes` ~ = `8.0009 PB`

HDD = `155177725730816(dev) + 252049810489344(test) + 32926980443784190(main) = 33334207980004350 bytes` ~ = `29.6067 PB`

RAM = `3522255826944(dev) + 6183874412544(test) + 420401556529152(main) = bytes` ~ = `391.18 TB`
